export default [
  [
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":2,
      "rowSpan":2,
      "location":[
        0,
        0
      ],
      "isEmpty":0,
      "isError":0,
      "style":{

      },
      "parentTdNode":[

      ],
      "childrenTdNode":[
        2,
        0
      ],
      "childrenProps":{
        "tagName":"TitleBox",
        "keyName":"A12345",
        "cnName":"A",
        "isSearch":0,
        "value":"",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string"
      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        0,
        1
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "style":{

      },
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":2,
      "location":[
        0,
        2
      ],
      "isEmpty":0,
      "isError":0,
      "style":{

      },
      "parentTdNode":[

      ],
      "childrenTdNode":[
        2,
        2
      ],
      "childrenProps":{
        "tagName":"TitleBox",
        "keyName":"B1234",
        "cnName":"B",
        "isSearch":0,
        "value":"",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string"
      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":2,
      "rowSpan":1,
      "location":[
        0,
        3
      ],
      "isEmpty":0,
      "isError":0,
      "style":{

      },
      "parentTdNode":[

      ],
      "childrenTdNode":[
        0,
        5
      ],
      "childrenProps":{
        "tagName":"TitleBox",
        "keyName":"C1234",
        "cnName":"C",
        "isSearch":0,
        "value":"",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string"
      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        0,
        4
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        0,
        5
      ],
      "isHidden":0,
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[
        0,
        3
      ],
      "childrenTdNode":[

      ],
      "childrenProps":{
        "tagName":"Radio",
        "value":[
          "33D5FB6BBF184D03A26B72D2C4CEAC3A"
        ],
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataListId":"816831398C2544EAAF0D8B717E472F49",
        "dataType":"string",
        "isMultiple":0,
        "validate":[
          {
            "key":"isRequire",
            "value":0,
            "name":"是否必选"
          },
          {
            "key":"max",
            "value":"",
            "name":"最大长度"
          },
          {
            "key":"min",
            "value":"",
            "name":"最小长度"
          },
          {
            "key":"event",
            "value":"blur",
            "name":"验证时间"
          }
        ]
      }
    }
  ],
  [
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        1,
        0
      ],
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      },
      "isHidden":1
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        1,
        1
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        1,
        2
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":2,
      "location":[
        1,
        3
      ],
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[
        3,
        3
      ],
      "childrenProps":{
        "tagName":"TitleBox",
        "keyName":"D1234",
        "cnName":"D",
        "isSearch":0,
        "value":"",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string"
      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":2,
      "location":[
        1,
        4
      ],
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[
        3,
        4
      ],
      "childrenProps":{
        "tagName":"TitleBox",
        "keyName":"E12345",
        "cnName":"E",
        "isSearch":0,
        "value":"",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string"
      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        1,
        5
      ],
      "isHidden":0,
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[
        2,
        5
      ],
      "childrenProps":{
        "tagName":"TitleBox",
        "keyName":"F123134",
        "cnName":"F",
        "isSearch":0,
        "value":"",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string"
      }
    }
  ],
  [
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":2,
      "rowSpan":2,
      "location":[
        2,
        0
      ],
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[
        0,
        0
      ],
      "childrenTdNode":[

      ],
      "childrenProps":{
        "tagName":"Input",
        "value":"AAAAAAAAAAAAAAAA",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string",
        "validate":[
          {
            "key":"isRequire",
            "value":0,
            "name":"是否必选",
            "event":[
              "change"
            ]
          },
          {
            "key":"max",
            "value":null,
            "name":"最大长度",
            "event":[
              "change"
            ]
          },
          {
            "key":"min",
            "value":null,
            "name":"最小长度",
            "event":[
              "change"
            ]
          }
        ]
      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        2,
        1
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":2,
      "location":[
        2,
        2
      ],
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[
        0,
        2
      ],
      "childrenTdNode":[

      ],
      "childrenProps":{
        "tagName":"TextArea",
        "value":"BBBBBBBBBBBBBBB",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string",
        "validate":[
          {
            "key":"isRequire",
            "value":0,
            "name":"是否必选",
            "event":[
              "change"
            ]
          },
          {
            "key":"max",
            "value":null,
            "name":"最大长度",
            "event":[
              "change"
            ]
          },
          {
            "key":"min",
            "value":null,
            "name":"最小长度",
            "event":[
              "change"
            ]
          }
        ]
      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        2,
        3
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        2,
        4
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        2,
        5
      ],
      "isHidden":0,
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[
        1,
        5
      ],
      "childrenTdNode":[

      ],
      "childrenProps":{
        "tagName":"Datepicker",
        "value":"2020-10-22",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string",
        "timeValidate":[
          {
            "key":"defaultValue",
            "name":"默认值",
            "value":"2020-11-05"
          },
          {
            "key":"startTime",
            "name":"开始时间",
            "value":""
          },
          {
            "key":"endTime",
            "name":"结束时间",
            "value":""
          }
        ]
      }
    }
  ],
  [
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        3,
        0
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        3,
        1
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        3,
        2
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        3,
        3
      ],
      "isHidden":0,
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[
        1,
        3
      ],
      "childrenTdNode":[

      ],
      "childrenProps":{
        "tagName":"Input",
        "value":"DDDDDDDDDDD",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string",
        "validate":[
          {
            "key":"isRequire",
            "value":0,
            "name":"是否必选",
            "event":[
              "change"
            ]
          },
          {
            "key":"max",
            "value":null,
            "name":"最大长度",
            "event":[
              "change"
            ]
          },
          {
            "key":"min",
            "value":null,
            "name":"最小长度",
            "event":[
              "change"
            ]
          }
        ]
      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        3,
        4
      ],
      "isHidden":0,
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[
        1,
        4
      ],
      "childrenTdNode":[

      ],
      "childrenProps":{
        "tagName":"Input",
        "value":"EEEEEEEEEEEEEE",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string",
        "validate":[
          {
            "key":"isRequire",
            "value":0,
            "name":"是否必选",
            "event":[
              "change"
            ]
          },
          {
            "key":"max",
            "value":null,
            "name":"最大长度",
            "event":[
              "change"
            ]
          },
          {
            "key":"min",
            "value":null,
            "name":"最小长度",
            "event":[
              "change"
            ]
          }
        ]
      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        3,
        5
      ],
      "isHidden":0,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    }
  ],
  [
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        4,
        0
      ],
      "isHidden":0,
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[
        5,
        0
      ],
      "childrenProps":{
        "tagName":"TitleBox",
        "keyName":"G12345",
        "cnName":"G",
        "isSearch":0,
        "value":"",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string"
      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        4,
        1
      ],
      "isHidden":0,
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[
        5,
        1
      ],
      "childrenProps":{
        "tagName":"TitleBox",
        "keyName":"h123445",
        "cnName":"H",
        "isSearch":0,
        "value":"",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string"
      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        4,
        2
      ],
      "isHidden":0,
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[
        5,
        2
      ],
      "childrenProps":{
        "tagName":"TitleBox",
        "keyName":"A1231231",
        "cnName":"I",
        "isSearch":0,
        "value":"",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string"
      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        4,
        3
      ],
      "isHidden":0,
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[
        5,
        3
      ],
      "childrenProps":{
        "tagName":"TitleBox",
        "keyName":"A123124314",
        "cnName":"J",
        "isSearch":0,
        "value":"",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string"
      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        4,
        4
      ],
      "isHidden":0,
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[
        5,
        4
      ],
      "childrenProps":{
        "tagName":"TitleBox",
        "keyName":"ADFASDFASDF",
        "cnName":"K",
        "isSearch":0,
        "value":"",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string"
      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        4,
        5
      ],
      "isHidden":0,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    }
  ],
  [
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        5,
        0
      ],
      "isHidden":0,
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[
        4,
        0
      ],
      "childrenTdNode":[

      ],
      "childrenProps":{
        "tagName":"Select",
        "value":[
          "A90E2653F143427183C6981633BEC701"
        ],
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataListId":"816831398C2544EAAF0D8B717E472F49",
        "dataType":"string",
        "isMultiple":0,
        "validate":[
          {
            "key":"isRequire",
            "value":0,
            "name":"是否必选"
          },
          {
            "key":"max",
            "value":"",
            "name":"最大长度"
          },
          {
            "key":"min",
            "value":"",
            "name":"最小长度"
          },
          {
            "key":"event",
            "value":"blur",
            "name":"验证时间"
          }
        ]
      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":4,
      "location":[
        5,
        1
      ],
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[
        4,
        1
      ],
      "childrenTdNode":[

      ],
      "childrenProps":{
        "tagName":"TextArea",
        "value":"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string",
        "validate":[
          {
            "key":"isRequire",
            "value":0,
            "name":"是否必选",
            "event":[
              "change"
            ]
          },
          {
            "key":"max",
            "value":null,
            "name":"最大长度",
            "event":[
              "change"
            ]
          },
          {
            "key":"min",
            "value":null,
            "name":"最小长度",
            "event":[
              "change"
            ]
          }
        ]
      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":2,
      "location":[
        5,
        2
      ],
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[
        4,
        2
      ],
      "childrenTdNode":[

      ],
      "childrenProps":{
        "tagName":"Select",
        "value":[
          "A90E2653F143427183C6981633BEC701"
        ],
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataListId":"816831398C2544EAAF0D8B717E472F49",
        "dataType":"string",
        "isMultiple":0,
        "validate":[
          {
            "key":"isRequire",
            "value":0,
            "name":"是否必选"
          },
          {
            "key":"max",
            "value":"",
            "name":"最大长度"
          },
          {
            "key":"min",
            "value":"",
            "name":"最小长度"
          },
          {
            "key":"event",
            "value":"blur",
            "name":"验证时间"
          }
        ]
      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":2,
      "location":[
        5,
        3
      ],
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[
        4,
        3
      ],
      "childrenTdNode":[

      ],
      "childrenProps":{
        "tagName":"Radio",
        "value":[
          "33D5FB6BBF184D03A26B72D2C4CEAC3A"
        ],
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataListId":"816831398C2544EAAF0D8B717E472F49",
        "dataType":"string",
        "isMultiple":0,
        "validate":[
          {
            "key":"isRequire",
            "value":0,
            "name":"是否必选"
          },
          {
            "key":"max",
            "value":"",
            "name":"最大长度"
          },
          {
            "key":"min",
            "value":"",
            "name":"最小长度"
          },
          {
            "key":"event",
            "value":"blur",
            "name":"验证时间"
          }
        ]
      }
    },
    {
      "tag":"td",
      "insertType":"col",
      "colSpan":1,
      "rowSpan":2,
      "location":[
        5,
        4
      ],
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[
        4,
        4
      ],
      "childrenTdNode":[

      ],
      "childrenProps":{
        "tagName":"Checkbox",
        "value":[
          "33D5FB6BBF184D03A26B72D2C4CEAC3A",
          "A90E2653F143427183C6981633BEC701"
        ],
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataListId":"816831398C2544EAAF0D8B717E472F49",
        "dataType":"string",
        "isMultiple":0,
        "validate":[
          {
            "key":"isRequire",
            "value":0,
            "name":"是否必选"
          },
          {
            "key":"max",
            "value":"",
            "name":"最大长度"
          },
          {
            "key":"min",
            "value":"",
            "name":"最小长度"
          },
          {
            "key":"event",
            "value":"blur",
            "name":"验证时间"
          }
        ]
      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        5,
        5
      ],
      "isHidden":0,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    }
  ],
  [
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        6,
        0
      ],
      "isHidden":0,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        6,
        1
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        6,
        2
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        6,
        3
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        6,
        4
      ],
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      },
      "isHidden":1
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        6,
        5
      ],
      "isHidden":0,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    }
  ],
  [
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        7,
        0
      ],
      "isHidden":0,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        7,
        1
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        7,
        2
      ],
      "isHidden":0,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        7,
        3
      ],
      "isHidden":0,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        7,
        4
      ],
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        7,
        5
      ],
      "isHidden":0,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    }
  ],
  [
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        8,
        0
      ],
      "isHidden":0,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        8,
        1
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        8,
        2
      ],
      "isHidden":0,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        8,
        3
      ],
      "isHidden":0,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        8,
        4
      ],
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":1,
      "location":[
        8,
        5
      ],
      "isHidden":0,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    }
  ],
  [
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":4,
      "location":[
        9,
        0
      ],
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[
        9,
        1
      ],
      "childrenProps":{
        "tagName":"TitleBox",
        "keyName":"AAAAA123123",
        "cnName":"jasdfasdfasdfasdf",
        "isSearch":0,
        "value":"",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string"
      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":3,
      "rowSpan":4,
      "location":[
        9,
        1
      ],
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[
        9,
        0
      ],
      "childrenTdNode":[

      ],
      "childrenProps":{
        "tagName":"TextArea",
        "value":"asdfasdfasdfasdfa",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string",
        "validate":[
          {
            "key":"isRequire",
            "value":0,
            "name":"是否必选",
            "event":[
              "change"
            ]
          },
          {
            "key":"max",
            "value":null,
            "name":"最大长度",
            "event":[
              "change"
            ]
          },
          {
            "key":"min",
            "value":null,
            "name":"最小长度",
            "event":[
              "change"
            ]
          }
        ]
      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        9,
        2
      ],
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      },
      "isHidden":1
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        9,
        3
      ],
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      },
      "isHidden":1
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":4,
      "location":[
        9,
        4
      ],
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[
        9,
        5
      ],
      "childrenProps":{
        "tagName":"TitleBox",
        "keyName":"E123123",
        "cnName":"姓名",
        "isSearch":0,
        "value":"",
        "style":{
          "fontSize":"14",
          "color":"#fafafa",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"#1a1919"
        },
        "placeholder":"",
        "dataType":"string"
      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":1,
      "rowSpan":4,
      "location":[
        9,
        5
      ],
      "isEmpty":0,
      "isError":0,
      "parentTdNode":[
        9,
        4
      ],
      "childrenTdNode":[

      ],
      "childrenProps":{
        "tagName":"TextArea",
        "value":"123123123",
        "style":{
          "fontSize":"14",
          "color":"#000",
          "justifyContent":"center",
          "alignItems":"center",
          "backgroundColor":"transparent"
        },
        "placeholder":"",
        "dataType":"string",
        "validate":[
          {
            "key":"isRequire",
            "value":0,
            "name":"是否必选",
            "event":[
              "change"
            ]
          },
          {
            "key":"max",
            "value":null,
            "name":"最大长度",
            "event":[
              "change"
            ]
          },
          {
            "key":"min",
            "value":null,
            "name":"最小长度",
            "event":[
              "change"
            ]
          }
        ]
      }
    }
  ],
  [
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        10,
        0
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        10,
        1
      ],
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      },
      "isHidden":1
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        10,
        2
      ],
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      },
      "isHidden":1
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        10,
        3
      ],
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      },
      "isHidden":1
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        10,
        4
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        10,
        5
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    }
  ],
  [
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        11,
        0
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        11,
        1
      ],
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      },
      "isHidden":1
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        11,
        2
      ],
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      },
      "isHidden":1
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        11,
        3
      ],
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      },
      "isHidden":1
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        11,
        4
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        11,
        5
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    }
  ],
  [
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        12,
        0
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        12,
        1
      ],
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      },
      "isHidden":1
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        12,
        2
      ],
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      },
      "isHidden":1
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        12,
        3
      ],
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      },
      "isHidden":1
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        12,
        4
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    },
    {
      "tag":"td",
      "insertType":"row",
      "colSpan":0,
      "rowSpan":0,
      "location":[
        12,
        5
      ],
      "isHidden":1,
      "isEmpty":1,
      "isError":0,
      "parentTdNode":[

      ],
      "childrenTdNode":[

      ],
      "childrenProps":{

      }
    }
  ]
]
